export const macKeyboardRU = [

        // {"key": "`", "code": "Backquote", "width": "1"},
        {"key": "ё", "code": "Backslash", "width": "1"},
        {"key": "1", "code": "Digit1", "width": "1"},
        {"key": "2", "code": "Digit2", "width": "1"},
        {"key": "3", "code": "Digit3", "width": "1"},
        {"key": "4", "code": "Digit4", "width": "1"},
        {"key": "5", "code": "Digit5", "width": "1"},
        {"key": "6", "code": "Digit6", "width": "1"},
        {"key": "7", "code": "Digit7", "width": "1"},
        {"key": "8", "code": "Digit8", "width": "1"},
        {"key": "9", "code": "Digit9", "width": "1"},
        {"key": "0", "code": "Digit0", "width": "1"},
        {"key": "-", "code": "Minus", "width": "1"},
        {"key": "=", "code": "Equal", "width": "1"},
        {"key": "Backspace", "code": "Backspace", "width": "2.3"},
        {"key": "Tab", "code": "Tab", "width": "1.15"},
        {"key": "й", "code": "KeyQ", "width": "1"},
        {"key": "ц", "code": "KeyW", "width": "1"},
        {"key": "у", "code": "KeyE", "width": "1"},
        {"key": "к", "code": "KeyR", "width": "1"},
        {"key": "е", "code": "KeyT", "width": "1"},
        {"key": "н", "code": "KeyY", "width": "1"},
        {"key": "г", "code": "KeyU", "width": "1"},
        {"key": "ш", "code": "KeyI", "width": "1"},
        {"key": "щ", "code": "KeyO", "width": "1"},
        {"key": "з", "code": "KeyP", "width": "1"},
        {"key": "х", "code": "BracketLeft", "width": "1"},
        {"key": "ъ", "code": "BracketRight", "width": "1"},
        {"key": "\\", "code": "Backslash", "width": "1"},
        {"key": "del", "code": "Delete", "width": "1"},

        {"key": "Caps Lock", "code": "CapsLock", "width": "2.25"},
        {"key": "ф", "code": "KeyA", "width": "1"},
        {"key": "ы", "code": "KeyS", "width": "1"},
        {"key": "в", "code": "KeyD", "width": "1"},
        {"key": "а", "code": "KeyF", "width": "1"},
        {"key": "п", "code": "KeyG", "width": "1"},
        {"key": "р", "code": "KeyH", "width": "1"},
        {"key": "о", "code": "KeyJ", "width": "1"},
        {"key": "л", "code": "KeyK", "width": "1"},
        {"key": "д", "code": "KeyL", "width": "1"},
        {"key": "ж", "code": "Semicolon", "width": "1"},
        {"key": "э", "code": "Quote", "width": "1"},
        {"key": "Enter", "code": "Enter", "width": "2.25"},
        {"key": "Shift", "code": "ShiftLeft", "width": "2.25"},
        {"key": "я", "code": "KeyZ", "width": "1"},
        {"key": "ч", "code": "KeyX", "width": "1"},
        {"key": "с", "code": "KeyC", "width": "1"},
        {"key": "м", "code": "KeyV", "width": "1"},
        {"key": "и", "code": "KeyB", "width": "1"},
        {"key": "т", "code": "KeyN", "width": "1"},
        {"key": "ь", "code": "KeyM", "width": "1"},
        {"key": "б", "code": "Comma", "width": "1"},
        {"key": "ю", "code": "Period", "width": "1"},
        {"key": "/", "code": "Slash", "width": "1"},
        {"key": "↑", "code": "ArrowUp", "width": "1"},
        {"key": "Shift", "code": "ShiftRight", "width": "2.25"},
        {"key": "Ctrl", "code": "ControlLeft", "width": "1"},
        {"key": "Option", "code": "AltLeft", "width": "1"},
        {"key": "Command", "code": "MetaLeft", "width": "1.5"},
        {"key": "&nbsp;", "code": "Space", "width": '5.95'},
        {"key": "Command", "code": "MetaRight", "width": "1.5"},
        {"key": "Option", "code": "AltRight", "width": "1"},
        {"key": "←", "code": "ArrowLeft", "width": "1"},
        {"key": "↓", "code": "ArrowDown", "width": "1"},
        {"key": "→", "code": "ArrowRight", "width": "1"},
        {"key": "Ctrl", "code": "ControlRight", "width": "1"},


]

