export const macKeyboardRU = [

    {"key": ">", 'keyEn': '§', 'shiftKey':'<', 'shiftKeyEn':'±', "code": "Backquote", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "1", 'keyEn': '1', 'shiftKey':'!', 'shiftKeyEn':'!', "code": "Digit1", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "2", 'keyEn': '2', 'shiftKey':'"', 'shiftKeyEn':'@', "code": "Digit2", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "3", 'keyEn': '3', 'shiftKey':'№', 'shiftKeyEn':'#', "code": "Digit3", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "4", 'keyEn': '4', 'shiftKey':'%', 'shiftKeyEn':'$', "code": "Digit4", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "5", 'keyEn': '5', 'shiftKey':':', 'shiftKeyEn':'%', "code": "Digit5", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "6", 'keyEn': '6', 'shiftKey':',', 'shiftKeyEn':'^', "code": "Digit6", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "7", 'keyEn': '7', 'shiftKey':'.', 'shiftKeyEn':'&', "code": "Digit7", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "8", 'keyEn': '8', 'shiftKey':'*', 'shiftKeyEn':'*', "code": "Digit8", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "9", 'keyEn': '9', 'shiftKey':'(', 'shiftKeyEn':'(', "code": "Digit9", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "0", 'keyEn': '0', 'shiftKey':')', 'shiftKeyEn':')', "code": "Digit0", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "-", 'keyEn': '-', 'shiftKey':'_', 'shiftKeyEn':'_', "code": "Minus", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "=", 'keyEn': '=', 'shiftKey':'+', 'shiftKeyEn':'+', "code": "Equal", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "Backspace", 'keyEn': 'Backspace', 'shiftKey':'', 'shiftKeyEn':'', "code": "Backspace", "width": "2.3", 'type': 'backspace'},
    {"key": "Tab", 'keyEn': 'Tab', 'shiftKey':'', 'shiftKeyEn':'', "code": "Tab", "width": "1.15", 'type': 'tab', 'lang' : 'false'},
    {"key": "й",'keyEn': 'q', 'shiftKey':"й", 'shiftKeyEn':'q',"code": "KeyQ", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "ц",'keyEn': 'w', 'shiftKey':"ц", 'shiftKeyEn':'w',"code": "KeyW", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "у",'keyEn': 'e', 'shiftKey':"у", 'shiftKeyEn':'e',"code": "KeyE", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "к",'keyEn': 'r', 'shiftKey':"к", 'shiftKeyEn':'r',"code": "KeyR", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "е",'keyEn': 't', 'shiftKey':"е", 'shiftKeyEn':'t',"code": "KeyT", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "н",'keyEn': 'y', 'shiftKey':"н", 'shiftKeyEn':'y',"code": "KeyY", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "г",'keyEn': 'u', 'shiftKey':"г", 'shiftKeyEn':'u',"code": "KeyU", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "ш",'keyEn': 'i', 'shiftKey':"ш", 'shiftKeyEn':'i',"code": "KeyI", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "щ",'keyEn': 'o', 'shiftKey':"щ", 'shiftKeyEn':'o',"code": "KeyO", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "з",'keyEn': 'p', 'shiftKey':"з", 'shiftKeyEn':'p',"code": "KeyP", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "х",'keyEn': '[', 'shiftKey':"х", 'shiftKeyEn':'{',"code": "BracketLeft", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "ъ",'keyEn': ']', 'shiftKey':"ъ", 'shiftKeyEn':'}',"code": "BracketRight", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "ё",'keyEn': '\\', 'shiftKey':"ё",'shiftKeyEn':'|', "code": "Backslash", "width": "1", 'type': '', 'lang' : 'false'},
    // {"key": "\\", 'shiftKey':'/', "code": "Backslash", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "del", 'keyEn': 'del', 'shiftKey':'', 'shiftKeyEn':'', "code": "Delete", "width": "1", 'type': 'del', 'lang' : 'false'},
    {"key": "Caps Lock", 'keyEn': 'Caps Lock', 'shiftKey':'', 'shiftKeyEn':'', "code": "CapsLock", "width": "2.25", 'type': 'caps', 'lang' : 'false'},
    {"key": "ф", 'keyEn': 'a','shiftKey':"ф",'shiftKeyEn':'a', "code": "KeyA", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "ы",'keyEn': 's', 'shiftKey':"ы",'shiftKeyEn':'s', "code": "KeyS", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "в",'keyEn': 'd', 'shiftKey':"в",'shiftKeyEn':'d', "code": "KeyD", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "а",'keyEn': 'f', 'shiftKey':"а",'shiftKeyEn':'f', "code": "KeyF", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "п", 'keyEn': 'g','shiftKey':"п",'shiftKeyEn':'g', "code": "KeyG", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "р",'keyEn': 'h', 'shiftKey':"р",'shiftKeyEn':'h', "code": "KeyH", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "о",'keyEn': 'j', 'shiftKey':"о",'shiftKeyEn':'j', "code": "KeyJ", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "л",'keyEn': 'k', 'shiftKey':"л",'shiftKeyEn':'k', "code": "KeyK", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "д",'keyEn': 'l', 'shiftKey':"д",'shiftKeyEn':'l', "code": "KeyL", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "ж",'keyEn': ';', 'shiftKey':"ж",'shiftKeyEn':':', "code": "Semicolon", "width": "1", 'type': '', 'lang' : 'false',},
    {"key": "э",'keyEn': ',', 'shiftKey':"э",'shiftKeyEn':'"', "code": "Quote", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "Enter", 'keyEn': 'Enter', 'shiftKey':'', 'shiftKeyEn':'', "code": "Enter", "width": "2.25", 'type': 'enter', 'lang' : 'false'},
    {"key": "Shift", 'keyEn': 'Shift', 'shiftKey':'', 'shiftKeyEn':'', "code": "ShiftLeft", "width": "2.25", 'type': 'shift', 'lang' : 'false'},
    {"key": "я",'keyEn': 'z', 'shiftKey':"я",'shiftKeyEn':'z', "code": "KeyZ", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "ч",'keyEn': 'x', 'shiftKey':"ч",'shiftKeyEn':'x', "code": "KeyX", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "с",'keyEn': 'c', 'shiftKey':"с",'shiftKeyEn':'c', "code": "KeyC", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "м",'keyEn': 'v', 'shiftKey':"м",'shiftKeyEn':'v', "code": "KeyV", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "и",'keyEn': 'b', 'shiftKey':"и",'shiftKeyEn':'b', "code": "KeyB", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "т",'keyEn': 'n', 'shiftKey':"т",'shiftKeyEn':'n', "code": "KeyN", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "ь",'keyEn': 'm', 'shiftKey':"ь",'shiftKeyEn':'m', "code": "KeyM", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "б",'keyEn': ',', 'shiftKey':"б",'shiftKeyEn':'<', "code": "Comma", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "ю",'keyEn': '.', 'shiftKey':"ю",'shiftKeyEn':'>', "code": "Period", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "/",'keyEn': '/', 'shiftKey':'?','shiftKeyEn':'?', "code": "Slash", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "↑",'keyEn': '↑', 'shiftKey':"↑",'shiftKeyEn':'↑', "code": "ArrowUp", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "Shift", 'keyEn': 'Shift', 'shiftKey':'', 'shiftKeyEn':'', "code": "ShiftRight", "width": "2.25", 'type': 'shift', 'lang' : 'false'},
    {"key": "Ctrl", 'keyEn': 'Ctrl', 'shiftKey':'', 'shiftKeyEn':'', "code": "ControlLeft", "width": "1", 'type': 'ctrl', 'lang' : 'true'},
    {"key": "Option", 'keyEn': 'Option', 'shiftKey':'', 'shiftKeyEn':'', "code": "AltLeft", "width": "1", 'type': 'option', 'lang' : 'true'},
    {"key": "Command", 'keyEn': 'Command', 'shiftKey':'', 'shiftKeyEn':'', "code": "MetaLeft", "width": "1.5", 'type': 'cmd', 'lang' : 'false'},
    {"key": ' ', 'keyEn': ' ', 'shiftKey':'', 'shiftKeyEn':'', "code": "Space", "width": '5.95', 'type': '', 'lang' : 'false'},
    {"key": "Command", 'keyEn': 'Command', 'shiftKey':'', 'shiftKeyEn':'', "code": "MetaRight", "width": "1.5", 'type': 'cmd', 'lang' : 'false'},
    {"key": "Option", 'keyEn': 'Option', 'shiftKey':'', 'shiftKeyEn':'', "code": "AltRight", "width": "1", 'type': 'option', 'lang' : 'false'},
    {"key": "←",'keyEn': '←', 'shiftKey':"←",'shiftKeyEn':'←', "code": "ArrowLeft", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "↓",'keyEn': '↓', 'shiftKey':"↓",'shiftKeyEn':'↓', "code": "ArrowDown", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "→",'keyEn': '→', 'shiftKey':"→",'shiftKeyEn':'→', "code": "ArrowRight", "width": "1", 'type': '', 'lang' : 'false'},
    {"key": "Ctrl", 'keyEn': 'Ctrl', 'shiftKey':'', 'shiftKeyEn':'', "code": "ControlRight", "width": "1", 'type': 'ctrl', 'lang' : 'false'},


]

